config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get "home/about"=>"homes#about"

  resources :today_tasks, only: [:index, :create, :edit, :update, :destroy]
  resources :month_tasks, only: [:index, :create, :edit, :update, :destroy]
  resources :users, only: [:edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/month_task.rb
class MonthTask < ApplicationRecord
  belongs_to :user
  
  validates :name, presence: true
  validates :content, presence: true, length: { maximum: 200 }
end

app/models/today_task.rb
class TodayTask < ApplicationRecord
  belongs_to :user
  
  validates :name, presence: true
  validates :content, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :today_tasks, dependent: :destroy
  has_many :month_tasks, dependent: :destroy
  attachment :profile_image
  
  validates :name, uniqueness: true, presence: true, length: { minimum: 2, maximum: 20 }
  validates :profession, length: { maximum: 50 }
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :authenticate_user!,except: [:top, :new, :create, :about]
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery
  
  def after_sign_in_path_for(resource)
    today_tasks_path
  end
  
  def after_sign_up_path_for(resource)
    month_tasks_path
  end
  
  

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/month_tasks_controller.rb
class MonthTasksController < ApplicationController
  def index
    @user = User.find(current_user.id)
    @month_task = MonthTask.new
    @month_tasks = current_user.month_tasks
  end
  
  def create
    @month_task = MonthTask.new(month_task_params)
    @month_tasks = current_user.month_tasks
    @month_task.user_id = current_user.id
    if @month_task.save
      redirect_to month_tasks_path, notice: 'You have created month task successfully!'
    else
      render :index
    end
  end
  
  def edit
    @month_task = MonthTask.find(params[:id])
    if @month_task.user.id == current_user.id
      render "edit"
    else
      redirect_to root_path
    end
  end
  
  def update
    @month_task = MonthTask.find(params[:id])
    if @month_task.update(month_task_params)
      redirect_to month_tasks_path, notice: 'You have updated month task successfully!'
    else
      render :edit
    end
  end
  
  def destroy
    month_task = MonthTask.find(params[:id])
    month_task.destroy
    redirect_to month_tasks_path
  end
  
  private
  
  def month_task_params
    params.require(:month_task).permit(:name, :content)
  end
end

app/controllers/today_tasks_controller.rb
class TodayTasksController < ApplicationController
  def index
    @user = User.find(current_user.id)
    @today_task = TodayTask.new
    @today_tasks = current_user.today_tasks
  end
  
  def create
    @today_task = TodayTask.new(today_task_params)
    @today_tasks = current_user.today_tasks
    @today_task.user_id = current_user.id
    if @today_task.save
      redirect_to today_tasks_path, notice: 'You have created today task successfully!'
    else
      render :index
    end
  end
  
  def edit
    @today_task = TodayTask.find(params[:id])
    if @today_task.user.id == current_user.id
      render "edit"
    else
      redirect_to root_path
    end
  end
  
  def update
    @today_task = TodayTask.find(params[:id])
    if @today_task.update(today_task_params)
      redirect_to today_tasks_path, notice: 'You have updated today task successfully!'
    else
      render :edit
    end
  end
  
  def destroy
    today_task = TodayTask.find(params[:id])
    today_task.destroy
    redirect_to today_tasks_path
  end
  
  private
  
  def today_task_params
    params.require(:today_task).permit(:name, :content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    @user = User.find(params[:id])
    if @user.id == current_user.id
      render "edit"
    else
      redirect_to root_path
    end
  end
  
  def update
    @user = User.find(current_user.id)
    if @user.update(user_params)
      redirect_to today_tasks_path, notice: 'You have updated user successfully!'
    else
      render :edit
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :profile_image, :profession)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/month_tasks_helper.rb
module MonthTasksHelper
end

app/helpers/today_tasks_helper.rb
module TodayTasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
<main>
  <p id="notice"></p>
  <div class="card text-center">
    <div class="card-header">
      開発者の紹介
    </div>
    <div class="card-body">
      <h5 class="card-title">初めまして。</h5>
      <p class="card-text">
        このアプリの創設者の吉本栄史です。僕は現役の大学3年生でプログラミングの勉強をしています。</br>
        このアプリも完全自作です。少しばかり大変なこともありましたが、とても楽しく制作できました。</br>
        もし少しでも興味を持っていただけたなら幸いです。Please, subscribe!
      </p>
      <a href="/users/sign_up" class="btn btn-outline-danger">新規登録はここから！</a>
    </div>
    <div class="card-footer text-muted">
      shieeeeee_01
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1><strong>やることリスト</strong>へようこそ!!</h1>
        <p><strong>やることリストでは</strong>, </p>
        <p>あなたは今日やるべきことと、月末までにやるべきことを視覚化できます。</p>
        <p>忘れないうちにここに書き出してタスクを終えられるようにしましょう！</p>
        
        
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <a class="btn btn-outline-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
          </div>
          <div class="row">
            <a class="btn btn-outline-danger btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todolists</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if user_signed_in? %>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="container-fluid">
            <a class="navbar-brand" href="/today_tasks"><strong>やることリスト</strong></a></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <%= link_to(edit_user_path(current_user.id), class: 'nav-link active') do %>
                    マイページ編集
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to today_tasks_path, class: 'nav-link' do %>
                    今日すること
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to month_tasks_path, class: 'nav-link' do %>
                    月末までにすること
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to(destroy_user_session_path, class: 'nav-link', method: :delete) do %>
                    ログアウト
                  <% end %>
                </li>
              </ul>
            </div>
          </div>
        </nav>
      <% else %>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="container-fluid">
            <a class="navbar-brand" href="/"><strong>やることリスト</strong></a></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <%= link_to root_path, class: 'nav-link active' do %>
                    Topページ
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to home_about_path, class: 'nav-link' do %>
                    Aboutページ
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_user_registration_path, class: 'nav-link' do %>
                    Sign upページ
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_user_session_path, class: 'nav-link' do %>
                    Log inページ
                  <% end %>
                </li>
              </ul>
            </div>
          </div>
        </nav>
      <% end %>
    </header>
    <body>
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>
      <%= yield %>
    </body>
    <footer>
      <div class="container mt-5">
  	    <div class="row">
    	    <div class="mx-auto">
    		    <p>やることやってから遊びましょう。</p>
    	    </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/month_tasks/edit.html.erb
<main>
  <p id="notice">
    <%= notice %>
  </p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		  <h1>Editing Month Task</h1>
  		  <div id="error_explanation">
          <% if @month_task.errors.any? %>
            <h3>
              <%= @month_task.errors.count %> errors prohibited this obj from being saved:
            </h3>
            <ul>
              <% @month_task.errors.full_messages.each do |message| %>
                <li>
                  <%= message %>
                </li>
              <% end %>
            </ul>
          <% end %>
        </div>
  		  <div class="form-field">
          <%= form_with model: @month_task, local:true do |f| %>
            <div class="form-group">
              <%= f.label 'book_title', 'Name' %>
              <%= f.text_field :name, :class => 'form-control book_title' %>
            </div>
            <div class="form-group">
              <%= f.label 'book_opinion', 'Content' %>
              <%= f.text_area :content, :class => 'form-control book_body' %>
            </div>
            <div class="form-group">
              <input type="submit" name="commit" value="Update MonthTask" class="btn btn-outline-dark" data-disable-with="Update MonthTask">
            </div>
          <% end %>
          
          <%= link_to "Back", month_tasks_path %>
        </div>
    </div>
  </div>
</main>

app/views/month_tasks/index.html.erb
<main>
  <p id="notice">
  </p>
  <div class="container px-5 px-sm-0">
    <div id="error_explanation">
      <% if @month_task.errors.any? %>
        <h3>
          <%= @month_task.errors.count %> errors prohibited this obj from being saved:
        </h3>
        <ul>
          <% @month_task.errors.full_messages.each do |message| %>
            <li>
              <%= message %>
            </li>
          <% end %>
        </ul>
      <% end %>
    </div>
    <div class="row">
      <div class="col-md-3">
        <h2>ユーザー情報</h2>
          <%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
        <table class="table">
          <tbody>
            <tr></tr>
            <tr>
              <th>name</th>
              <th><%= current_user.name %></th>
            </tr>
            <tr class="marginb">
              <th>professsion</th>
              <th><%= current_user.profession %></th>
            </tr>
          </tbody>
        </table>
        
        <h2 class="mt-3">月末までのタスク追加</h2>
        <div class="form-field">
          <%= form_with model: @month_task, local:true do |f| %>
            <div class="form-group">
              <%= f.label 'book_title', 'Name' %>
              <%= f.text_field :name, :class => 'form-control book_title' %>
            </div>
            <div class="form-group">
              <%= f.label 'book_opinion', 'Content' %>
              <%= f.text_area :content, :class => 'form-control book_body' %>
            </div>
            <div class="form-group">
              <input type="submit" name="commit" value="Create MonthTask" class="btn btn-outline-primary" data-disable-with="Create MonthTask">
            </div>
          <% end %>
        </div>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>月末までに行うタスク</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th>Name</th>
              <th>Content</th>
              <th colspan="3"></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @month_tasks.each do |month_task| %>
              <tr>
                <td><%= month_task.name %></td>
                <td><%= month_task.content %></td>
                <td>
                  <%= link_to("Edit", edit_month_task_path(month_task.id), class: 'btn btn-sm btn-outline-success edit_book_12089') %>
                </td>
                <td>
                  <%= link_to("Destroy", month_task_path(month_task.id), { method: :delete, data: {confirm: "本当に消しますか？"}, class: 'btn btn-sm btn-warning destroy_book_12089'})%>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/today_tasks/edit.html.erb
<main>
  <p id="notice">
    <%= notice %>
  </p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		  <h1>Editing Today Task</h1>
  		  <div id="error_explanation">
          <% if @today_task.errors.any? %>
            <h3>
              <%= @today_task.errors.count %> errors prohibited this obj from being saved:
            </h3>
            <ul>
              <% @today_task.errors.full_messages.each do |message| %>
                <li>
                  <%= message %>
                </li>
              <% end %>
            </ul>
          <% end %>
        </div>
  		  <div class="form-field">
          <%= form_with model: @today_task, local:true do |f| %>
            <div class="form-group">
              <%= f.label 'book_title', 'Name' %>
              <%= f.text_field :name, :class => 'form-control book_title' %>
            </div>
            <div class="form-group">
              <%= f.label 'book_opinion', 'Content' %>
              <%= f.text_area :content, :class => 'form-control book_body' %>
            </div>
            <div class="form-group">
              <input type="submit" name="commit" value="Update TodayTask" class="btn btn-outline-dark" data-disable-with="Update TodayTask">
            </div>
          <% end %>
          
          <%= link_to "Back", today_tasks_path %>
        </div>
    </div>
  </div>
</main>

app/views/today_tasks/index.html.erb
<main>
  <p id="notice">
  </p>
  <div class="container px-5 px-sm-0">
    <div id="error_explanation">
      <% if @today_task.errors.any? %>
        <h3>
          <%= @today_task.errors.count %> errors prohibited this obj from being saved:
        </h3>
        <ul>
          <% @today_task.errors.full_messages.each do |message| %>
            <li>
              <%= message %>
            </li>
          <% end %>
        </ul>
      <% end %>
    </div>
    <div class="row">
      <div class="col-md-3">
        <h2>ユーザー情報</h2>
        <%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
        <table class="table">
          <tbody>
            <tr></tr>
            <tr>
              <th>name</th>
              <th><%= current_user.name %></th>
            </tr>
            <tr class="marginb">
              <th>professsion</th>
              <th><%= current_user.profession %></th>
            </tr>
          </tbody>
        </table>
        
        <h2 class="mt-3">今日のタスク追加</h2>
        <div class="form-field">
          <%= form_with model: @today_task, local:true do |f| %>
            <div class="form-group">
              <%= f.label 'book_title', 'Name' %>
              <%= f.text_field :name, :class => 'form-control book_title' %>
            </div>
            <div class="form-group">
              <%= f.label 'book_opinion', 'Content' %>
              <%= f.text_area :content, :class => 'form-control book_body' %>
            </div>
            <div class="form-group">
              <input type="submit" name="commit" value="Create TodayTask" class="btn btn-outline-primary" data-disable-with="Create TodayTask">
            </div>
          <% end %>
        </div>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>今日までに行うタスク</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th>Name</th>
              <th>Content</th>
              <th colspan="3"></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @today_tasks.each do |today_task| %>
              <tr>
                <td><%= today_task.name %></td>
                <td><%= today_task.content %></td>
                <td>
                  <%= link_to("Edit", edit_today_task_path(today_task.id), class: 'btn btn-sm btn-outline-success edit_book_12089') %>
                </td>
                <td>
                  <%= link_to("Destroy", today_task_path(today_task.id), { method: :delete, data: {confirm: "本当に消しますか？"}, class: 'btn btn-sm btn-warning destroy_book_12089'})%>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/users/edit.html.erb
<main>
  <p id="notice">
    
  </p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		  <h2>Editing Profile</h2>
  		  <div id="error_explanation">
          <% if @user.errors.any? %>
            <h3>
              <%= @user.errors.count %> errors prohibited this obj from being saved:
            </h3>
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li>
                  <%= message %>
                </li>
              <% end %>
            </ul>
          <% end %>
        </div>
  		  <div class="form-field">
          <%= form_with model: @user, local:true do |f| %>
            <div class="form-group">
              <%= f.label 'user_name', 'Name' %>
              <%= f.text_field :name, :class => 'form-control name' %>
            </div>
            <div class="form-group">
              <%= f.label 'user_image', 'Image' %>
              <%= f.attachment_field :profile_image, :class => 'form-control-file user_image' %>
            </div>
            <div class="form-group">
              <%= f.label 'user_introduction', 'Profession' %>
              <%= f.text_area :profession, :class => 'form-control introduction' %>
            </div>
            <div class="form-group">
              <input type="submit" name="commit" value="Update User" class="btn btn-secondary" data-disable-with="Update User">
            </div>
          <% end %>
        </div>
    </div>
  </div>
</main>